import { AppDataSource } from "./config/data-source";
import { AuthService } from "./service/AuthService";
import { CalculationService } from "./service/CalculationService";
import * as dotenv from "dotenv";

dotenv.config();

async function testCalculationModule() {
    console.log("Initializing database connection...");
    await AppDataSource.initialize();

    const mockEmail = `calcuser_${Date.now()}@example.com`;
    
    // Create a mock user to bind calculations to
    await AuthService.register({
        first_name: "Calc",
        last_name: "Tester",
        email: mockEmail,
        password: "password123"
    });
    
    // Login to obtain the exact user ID generated by DB
    const loginResult = await AuthService.login({ email: mockEmail, password: "password123" });
    const userId = loginResult.user.id;
    
    console.log(`✅ Created Mock User with ID: ${userId}`);

    console.log("\n[1] Testing Addition (+)...");
    const addResult = await CalculationService.performCalculation(userId, 10, '+', 5);
    console.log(`   Calculation Result: 10 + 5 = ${addResult.result}`);

    console.log("\n[2] Testing Multiplication (*)...");
    const mulResult = await CalculationService.performCalculation(userId, 6, '*', 7);
    console.log(`   Calculation Result: 6 * 7 = ${mulResult.result}`);

    console.log("\n[3] Testing Division by Zero constraint...");
    try {
        await CalculationService.performCalculation(userId, 10, '/', 0);
    } catch (e: any) {
        console.log(`   ✅ Successfully caught constraint error: ${e.message}`);
    }

    console.log("\n[4] Testing History Fetch...");
    const history = await CalculationService.getHistory(userId);
    console.log(`   Fetched ${history.length} valid calculation history records sequentially:`);
    history.forEach(h => {
        console.log(`   -> ${h.operand1} ${h.operator} ${h.operand2} = ${h.result}`);
    });

    await AppDataSource.destroy();
    console.log("\nDatabase connection closed. ✨ Test complete!");
}

testCalculationModule().catch(console.error);
